name: Cleanup Old Images
on:
  schedule:
    - cron: "0 0 * * 0" # 0000 UTC on Sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [devbox]
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@v1.0.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: ${{ matrix.package }}
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 20
          keep-n-untagged: 20
