name: Cleanup Old Images
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
jobs:
  delete-older-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [
            devbox,
            # devbox-fat,
            # devbox-nvidia,
            devbox-minimal,
          ]
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@v1.0.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: ideal-enigma/${{ matrix.package }}
          older-than: 90 days
          delete-orphaned-images: true
