name: Cleanup Old Images
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
jobs:
  delete-older-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix: [
            "",
            # "-nvidia"
          ]
    permissions:
      packages: write
    steps:
      - name: Clean up images for package ${{ github.event.repository.name }}${{ matrix.suffix }}
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: ${{ github.event.repository.name }}${{ matrix.package }}
          older-than: 60 days
          keep-n-tagged: 3
          delete-orphaned-images: true
          delete-partial-images: true
