name: Build Containers

on:
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  build-push-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ["Dockerfile.devbox"]
        tag: ["devbox"]
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Git metadata
        id: git-info
        run: |
          # Extract branch or tag name
          if [ "${{ github.ref_type }}" == "branch" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=commit-${{ github.sha }}" >> $GITHUB_ENV
          fi
          echo "SHORT_SHA=${{ github.sha:0:7 }}" >> $GITHUB_ENV

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Build and tag the Docker image
      - name: Build Docker image
        run: |
          docker build -f ${{ matrix.dockerfile }} \
          -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/${{ matrix.tag }}:${{ env.VERSION }} \
          -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/${{ matrix.tag }}:latest .

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/${{ matrix.tag }}:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/${{ matrix.tag }}:latest
