name: Build Containers
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

permissions:
  contents: read
  packages: write

jobs:
  build-push-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - name: devbox
            file: ./Containerfile.devbox
          - name: devbox-minimal
            file: ./Containerfile.minimal.devbox

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export lowercase image names
        shell: bash
        run: |
          : "ghcr.io/${{ github.repository }}/${{ matrix.container.name }}"
          echo "IMAGE_NAME=${_,,}" >> $GITHUB_ENV

      - name: Extract Git metadata
        id: git-info
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/testing" ]; then
            echo "VERSION=testing" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "VERSION=stable" >> $GITHUB_ENV
            # ensure "latest" tag is pinned to main branch only
            echo "LATEST_TAG=${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push container images
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ matrix.container.file }}
          platforms: linux/amd64
          push: true
          cache-from: type=gha,scope=${{ matrix.container.name }}
          cache-to: type=gha,scope=${{ matrix.container.name }},mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.LATEST_TAG }}
