name: Build Containers

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  workflow_dispatch: # allow manual trigger

jobs:
  build-push-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Git metadata
        id: git-info
        run: |
          # Extract tag or commit-sha
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Login to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push container images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile.devbox
          platforms: linux/amd64
          push: true
          outputs: |
            type=image,name=ghcr.io/wombatfromhell/devbox:${{ env.VERSION }},name=ghcr.io/wombatfromhell/devbox:latest
