name: Build Containers

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  workflow_dispatch: # allow manual trigger

jobs:
  build-push-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ["Containerfile.devbox"]
        tag: ["devbox"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Git metadata
        id: git-info
        run: |
          # Extract tag or commit-sha
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build Docker images
        run: |
          docker build -f ${{ matrix.dockerfile }} \
          -t ghcr.io/wombatfromhell/${{ matrix.tag }}:${{ env.VERSION }} \
          -t ghcr.io/wombatfromhell/${{ matrix.tag }}:latest .

      - name: Login to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push images to registry
        run: |
          docker push ghcr.io/${{ github.actor }}/${{ matrix.tag }}:${{ env.VERSION }}
          docker push ghcr.io/${{ github.actor }}/${{ matrix.tag }}:latest
