name: Build Containers

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  workflow_dispatch: # allow manual trigger

jobs:
  build-push-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ["Dockerfile.devbox"]
        tag: ["devbox"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Git metadata
        id: git-info
        run: |
          # Extract tag or commit-sha
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker images
        run: |
          docker build -f ${{ matrix.dockerfile }} \
          -t ghcr.io/wombatfromhell/${{ matrix.tag }}:${{ env.VERSION }} \
          -t ghcr.io/wombatfromhell/${{ matrix.tag }}:latest

      - name: Push Docker images
        run: |
          docker push ghcr.io/wombatfromhell/${{ matrix.tag }}:${{ env.VERSION }}
          docker push ghcr.io/wombatfromhell/${{ matrix.tag }}:latest
