name: Trivy Scan ghcr.io Image

on:
  workflow_dispatch: # when manually triggered
  #schedule:
  #  - cron: "0 3 */14 * *" # once every 14 days @ 0300 UTC

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [devbox]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          version: v0.57.1

      - name: Authenticate with ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from ghcr.io
        run: |
          docker pull ghcr.io/${{ github.repository }}/${{ matrix.package }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: "ghcr.io/${{ github.repository }}/${{ matrix.container.name }}:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          cache: true

      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt
          retention-days: 30

      - name: Display Trivy results
        run: |
          if [ -f trivy-report.txt ]; then
            echo "Trivy Scan Results:"
            cat trivy-report.txt
          else
            echo "No Trivy report generated."
          fi
