name: Trivy Scan ghcr.io Image

on:
  workflow_dispatch: # when manually triggered
  #schedule:
  #  - cron: "0 3 */14 * *" # once every 14 days @ 0300 UTC

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [devbox]

    permissions:
      packages: read
      security-events: write
      contents: read

    steps:
      - name: Lowercase repo name
        run: |
          echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "image"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          image-ref: "ghcr.io/${{ env.REPO }}/${{ matrix.package }}:latest"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
          category: "Trivy Container Scan"

      - name: Fail on CRITICAL vulnerabilities
        if: ${{ failure() }}
        run: |
          echo "Critical vulnerabilities found in container images"
          exit 1
